services: ["docker"]
script: script/travis
sudo: required
os: linux
cache:
  bundler: true
  directories:
    - vendor/bundle
env:
  global:
    - DOCKER_EMAIL=jekyllbot@jekyllrb.com
    - DOCKER_USERNAME=jekyllbot
    - secure: "\
        MA62JC8Fp1ww4ui3Wphy9bXaZymez5qEDsX5PKNy+Q7EZx++BhAOQVMugwdN2bpuiP5G6x\
        JX/DKOQ3fGUFAgYe5TZJgLt+DYTc+i+JU+2twPOfh98OseFWgRk4SnrbpxtcBYt4I8Iv1o\
        tjdW4P0aAGAvA1YYopGE70+WTrqixeY=\
      "
jobs:
  include:
    - script: true
      stage: precache
    - stage: build
      env: "\
        DOCKER_REPO='jekyll:3.5.2 \
          jekyll:3.5 \
          jekyll:stable \
          jekyll:latest \
          jekyll:3\
        '\
      "
    - env: DOCKER_REPO=jekyll:3.5.1
    - env: DOCKER_REPO=jekyll:3.5.0
    - env: "\
        DOCKER_REPO='jekyll:3.4.4 \
          jekyll:3.4\
        '\
      "
    - env: DOCKER_REPO=jekyll:3.4.3
    - env: DOCKER_REPO=jekyll:3.4.2
    - env: DOCKER_REPO=jekyll:3.4.1
    - env: DOCKER_REPO=jekyll:3.4.0
    - env: "\
        DOCKER_REPO='jekyll:3.3.1 \
          jekyll:3.3\
        '\
      "
    - env: DOCKER_REPO=jekyll:3.3.0
    - env: "\
        DOCKER_REPO='jekyll:3.2.1 \
          jekyll:3.2\
        '\
      "
    - env: DOCKER_REPO=jekyll:3.2.0
    - env: "\
        DOCKER_REPO='jekyll:3.1.6 \
          jekyll:3.1\
        '\
      "
    - env: DOCKER_REPO=jekyll:3.1.5
    - env: DOCKER_REPO=jekyll:3.1.4
    - env: DOCKER_REPO=jekyll:3.1.3
    - env: DOCKER_REPO=jekyll:3.1.2
    - env: DOCKER_REPO=jekyll:3.1.1
    - env: DOCKER_REPO=jekyll:3.1.0
    - env: "\
      DOCKER_REPO='jekyll:3.0.5 \
        jekyll:3.0\
      '\
    "
    - env: DOCKER_REPO=jekyll:3.0.4
    - env: DOCKER_REPO=jekyll:3.0.3
    - env: DOCKER_REPO=jekyll:3.0.2
    - env: DOCKER_REPO=jekyll:3.0.1
    - env: DOCKER_REPO=jekyll:3.0.0
    - env: DOCKER_REPO=jekyll:pages
    - env: "\
        DOCKER_REPO='builder:3.5.0 \
          builder:3.5 \
          builder:stable \
          builder:latest \
          builder:3\
        '\
      "
    - env: "\
        DOCKER_REPO='builder:3.4.4 \
          builder:3.4\
        '\
      "
    - env: DOCKER_REPO=builder:3.4.3
    - env: DOCKER_REPO=builder:3.4.2
    - env: DOCKER_REPO=builder:3.4.1
    - env: DOCKER_REPO=builder:3.4.0
    - env: "\
        DOCKER_REPO='builder:3.3.1 \
          builder:3.3\
        '\
      "
    - env: DOCKER_REPO=builder:3.3.0
    - env: "\
        DOCKER_REPO='builder:3.2.1 \
          builder:3.2\
        '\
      "
    - env: DOCKER_REPO=builder:3.2.0
    - env: "\
        DOCKER_REPO='builder:3.1.6 \
          builder:3.1\
        '\
      "
    - env: DOCKER_REPO=builder:3.1.5
    - env: DOCKER_REPO=builder:3.1.4
    - env: DOCKER_REPO=builder:3.1.3
    - env: DOCKER_REPO=builder:3.1.2
    - env: DOCKER_REPO=builder:3.1.1
    - env: DOCKER_REPO=builder:3.1.0
    - env: "\
      DOCKER_REPO='builder:3.0.5 \
        builder:3.0\
      '\
    "
    - env: DOCKER_REPO=builder:3.0.4
    - env: DOCKER_REPO=builder:3.0.3
    - env: DOCKER_REPO=builder:3.0.2
    - env: DOCKER_REPO=builder:3.0.1
    - env: DOCKER_REPO=builder:3.0.0
    - env: DOCKER_REPO=builder:pages
    - env: "\
        DOCKER_REPO='minimal:3.5.0 \
          minimal:3.5 \
          minimal:stable \
          minimal:latest \
          minimal:3\
        '\
      "
    - env: "\
        DOCKER_REPO='minimal:3.4.4 \
          minimal:3.4\
        '\
      "
    - env: DOCKER_REPO=minimal:3.4.3
    - env: DOCKER_REPO=minimal:3.4.2
    - env: DOCKER_REPO=minimal:3.4.1
    - env: DOCKER_REPO=minimal:3.4.0
    - env: "\
        DOCKER_REPO='minimal:3.3.1 \
          minimal:3.3\
        '\
      "
    - env: DOCKER_REPO=minimal:3.3.0
    - env: "\
        DOCKER_REPO='minimal:3.2.1 \
          minimal:3.2\
        '\
      "
    - env: DOCKER_REPO=minimal:3.2.0
    - env: "\
        DOCKER_REPO='minimal:3.1.6 \
          minimal:3.1\
        '\
      "
    - env: DOCKER_REPO=minimal:3.1.5
    - env: DOCKER_REPO=minimal:3.1.4
    - env: DOCKER_REPO=minimal:3.1.3
    - env: DOCKER_REPO=minimal:3.1.2
    - env: DOCKER_REPO=minimal:3.1.1
    - env: DOCKER_REPO=minimal:3.1.0
    - env: "\
      DOCKER_REPO='minimal:3.0.5 \
        minimal:3.0\
      '\
    "
    - env: DOCKER_REPO=minimal:3.0.4
    - env: DOCKER_REPO=minimal:3.0.3
    - env: DOCKER_REPO=minimal:3.0.2
    - env: DOCKER_REPO=minimal:3.0.1
    - env: DOCKER_REPO=minimal:3.0.0
    - env: DOCKER_REPO=minimal:pages
