services: ["docker"]
sudo: required
os: linux
rvm:
  - 2.3.0
env:
  global:
    - DOCKER_EMAIL=jekyllbot@jekyllrb.com
    - DOCKER_USERNAME=jekyllbot
    - secure: "\
        MA62JC8Fp1ww4ui3Wphy9bXaZymez5qEDsX5PKNy+Q7EZx++BhAOQVMugwdN2bpuiP5G6x\
        JX/DKOQ3fGUFAgYe5TZJgLt+DYTc+i+JU+2twPOfh98OseFWgRk4SnrbpxtcBYt4I8Iv1o\
        tjdW4P0aAGAvA1YYopGE70+WTrqixeY=\
      "
  matrix:
    - DOCKER_REPO=jekyll
    - DOCKER_REPO=builder
jobs:
  include:
    - { stage: Test, script: script/test }
    - { stage: Build, script: script/build }
    - { stage: Deploy, script: script/deploy }
