services: docker
script: script/travis
sudo: required
language: ruby
os: linux
cache:
  bundler: true
  directories:
  - vendor/bundle
branches:
  only:
  - master
env:
  global:
  - DOCKER_EMAIL=alban.boye1@gmail.com
  - DOCKER_USERNAME=blafy
jobs:
  include:
  - script: true
    stage: precache
  - stage: build
    # --
    # jekyll/jekyll
    # --
    env: "\
      DOCKER_REPO='\
        jekyll:3.8.5 \
        jekyll:stable \
        jekyll:latest \
        jekyll:pages \
        jekyll:3.8 \
        jekyll:3\
      '\
    "
