services: ["docker"]
sudo: required
os: linux
rvm:
  - 2.3.0
env:
  global:
    - DOCKER_EMAIL=jekyllbot@jekyllrb.com
    - DOCKER_USERNAME=jekyllbot
    - secure: "\
        MA62JC8Fp1ww4ui3Wphy9bXaZymez5qEDsX5PKNy+Q7EZx++BhAOQVMugwdN2bpuiP5G6x\
        JX/DKOQ3fGUFAgYe5TZJgLt+DYTc+i+JU+2twPOfh98OseFWgRk4SnrbpxtcBYt4I8Iv1o\
        tjdW4P0aAGAvA1YYopGE70+WTrqixeY=\
      "
  matrix:
    - DOCKER_REPO=jekyll:pages
    - DOCKER_REPO=builder:pages
    - DOCKER_REPO=jekyll:3.3.0
    - DOCKER_REPO=builder:3.3.0
    - DOCKER_REPO=jekyll:3.3.1
    - DOCKER_REPO=builder:3.3.1
    - DOCKER_REPO=jekyll:3.4.0
    - DOCKER_REPO=builder:3.4.0
    - DOCKER_REPO=jekyll:3.4.1
    - DOCKER_REPO=builder:3.4.1
    - DOCKER_REPO=jekyll:3.4.2
    - DOCKER_REPO=builder:3.4.2
    - DOCKER_REPO=jekyll:3.4.3
    - DOCKER_REPO=builder:3.4.3
    - DOCKER_REPO=jekyll:latest
    - DOCKER_REPO=builder:latest
    - DOCKER_REPO=jekyll:stable
    - DOCKER_REPO=builder:stable
    - DOCKER_REPO=jekyll:3.4
    - DOCKER_REPO=builder:3.4
    - DOCKER_REPO=jekyll:3
    - DOCKER_REPO=builder:3
