services: docker
script: script/travis
sudo: required
language: ruby
os: linux
cache:
  bundler: true
  directories:
  - vendor/bundle
branches:
  only:
  - master
env:
  global:
  - DOCKER_EMAIL=jekyllbot@jekyllrb.com
  - DOCKER_USERNAME=jekyllbot
  - secure: "\
      MA62JC8Fp1ww4ui3Wphy9bXaZymez5qEDsX5PKNy+Q7EZx++BhAOQVMugwdN2bpuiP5G6x\
      JX/DKOQ3fGUFAgYe5TZJgLt+DYTc+i+JU+2twPOfh98OseFWgRk4SnrbpxtcBYt4I8Iv1o\
      tjdW4P0aAGAvA1YYopGE70+WTrqixeY=\
    "
jobs:
  include:
  - script: true
    stage: precache
  - stage: build
    # --
    # jekyll/jekyll
    # --
    env: "\
      DOCKER_REPO='jekyll:3.6.0 \
        jekyll:3.6 \
        jekyll:stable \
        jekyll:latest \
        jekyll:3\
      '\
    "
  - env: DOCKER_REPO=jekyll:pages
  # --
  # jekyll/builder
  # --
    env: "\
      DOCKER_REPO='builder:3.6.0 \
        builder:3.6 \
        builder:stable \
        builder:latest \
        builder:3\
      '\
    "
  - env: DOCKER_REPO=builder:pages
  # --
  # jekyll/minimal
  # --
    env: "\
      DOCKER_REPO='minimal:3.6.0 \
        minimal:3.6 \
        minimal:stable \
        minimal:latest \
        minimal:3\
      '\
    "
  - env: DOCKER_REPO=minimal:pages
